name: LaTeX Build and Lint

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    schedule:
      # Schedule to run at 00:00 UTC on the 1st of every month
      - cron: '0 0 1 * *'
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Git repository
      uses: actions/checkout@v3

    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-science texlive-extra-utils
    
    - name: Verify latexindent installation
      run: |
        latexindent --version

    - name: Check LaTeX formatting
      working-directory: latex
      run: make check

    - name: Compile LaTeX documents
      working-directory: latex
      run: make all

    - name: Check LaTeX formatting
      working-directory: hw
      run: make check

    - name: Compile LaTeX documents
      working-directory: hw
      run: make all

    - name: Upload Project PDFs
      uses: actions/upload-artifact@v3
      with:
        name: project-pdfs
        path: latex/*.pdf

    - name: Upload HW PDFs
      uses: actions/upload-artifact@v3
      with:
        name: hw-pdfs
        path: hw/*.pdf
  
