name: Proj3B

on:
    push:
      branches: [ main ]
    pull_request:
      branches: [ main ]
    schedule:
      # Schedule to run at 00:00 UTC on the 1st of every month
      - cron: '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Jimver/cuda-toolkit@v0.2.19
        id: cuda-toolkit
        with:
          cuda: "12.0.0"
      - name: Compile Proj3B
        run: |
          cd proj/proj3/proj3b
          make
      - name: Run Proj3B
        run: |
          cd proj/proj3/proj3b
          ./test.sh
