name: Proj1A

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
    - name: Compile Proj1A
      run: |
        cd proj/proj1/proj1a
        make
    - name: Run Proj1A
      run: |
        cd proj/proj1/proj1a
        ./test.sh
        ./benchmark.sh