name: Proj2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  
jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    container: 
      image: pli11/gpgpusim:cuda_10_1
      options: --user root
    env:
      CUDA_INSTALL_PATH: /usr/local/cuda-10.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set CUDA path globally
      run: |
        echo "CUDA_INSTALL_PATH=/usr/local/cuda-10.1" >> $GITHUB_ENV
        echo "CUDA_PATH=$CUDA_INSTALL_PATH" >> $GITHUB_ENV
        echo "PATH=$CUDA_INSTALL_PATH/bin:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Copy repository contents to container
      run: |
        mkdir -p /workspace
        cp -R $GITHUB_WORKSPACE/* /workspace/
      shell: bash
    
    - name: Build and Run Task 1
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        cd /root/gpgpu-sim_distribution
        git checkout tags/v4.0.1 -b v401
        cp /workspace/proj/proj2/cuda-sim/instructions.cc /root/gpgpu-sim_distribution/src/cuda-sim/instructions.cc
        cp /workspace/proj/proj2/vectorAdd.cu /root/vectorAdd.cu
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* .
        nvcc -arch=sm_70 -o vectorAdd vectorAdd.cu
        ./vectorAdd > output.txt
      shell: bash
    
    - name: Build and Run Task 2
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        cd /root/gpgpu-sim_distribution
        git checkout -- .
        make -j
        mkdir -p test
        cp -r /workspace/proj/proj2/ISPASS.zip test/
        cd test
        unzip ISPASS.zip
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM6_TITANX/* .
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_TITANV/* .
        # Assuming ISPASS contains directories for each benchmark
        for benchmark in BFS LIB LPS NN NQU; do
          cd $benchmark
          ln -sf ../../SM6_TITANX/gpgpusim.config .
          ln -sf ../../SM6_TITANX/config_fermi_islip.icnt .
          ln -sf ../../SM7_TITANV/gpgpusim.config .
          ln -sf ../../SM7_TITANV/config_volta_islip.icnt .
          # Specific commands for each benchmark
          case $benchmark in
            BFS)
              ./ispass-2009-BFS graph65536.txt
              ;;
            LIB)
              ./ispass-2009-LIB
              ;;
            LPS)
              ./ispass-2009-LPS
              ;;
            NN)
              mkdir -p data/
              cp ../../lw*.wei data/
              cp ../../t10k-images-idx3-ubyte data/
              ./ispass-2009-NN 28
              ;;
            NQU)
              ./ispass-2009-NQU
              ;;
          esac
          cd ..
        done
      shell: bash

    - name: Build and Run Task 3
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        cd /root/gpgpu-sim_distribution
        git checkout tags/v4.0.1 -b v401
        cp /workspace/proj/proj2/gpgpu-sim/shader.cc /root/gpgpu-sim_distribution/src/gpgpu-sim/gpgpu-sim/task3/shader.cc
        cp /workspace/proj/proj2/gpgpu-sim/shader.h /root/gpgpu-sim_distribution/src/gpgpu-sim/gpgpu-sim/task3/shader.h
        make -j
        cd /root/vectorAdd
        make -j
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* .
        nvcc -arch=sm_70 -o vectorAdd vectorAdd.cu
        ./vectorAdd > output.txt
      shell: bash

    - name: Build and Run Task 4
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        git checkout tags/v4.0.1 -b v401
        cp /workspace/proj/proj2/gpgpu-sim/shader.cc /root/gpgpu-sim_distribution/src/gpgpu-sim/gpgpu-sim/task4/shader.cc
        cp /workspace/proj/proj2/gpgpu-sim/shader.h /root/gpgpu-sim_distribution/src/gpgpu-sim/gpgpu-sim/task4/shader.h
        cd /root/gpgpu-sim_distribution
        make -j
        cd /root/vectorAdd
        make -j
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* .
        nvcc -arch=sm_70 -o vectorAdd vectorAdd.cu
        ./vectorAdd > output.txt
      shell: bash