name: Proj1B

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    env:
      CUDA_INSTALL_PATH: /usr/local/cuda-10.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
      shell: bash

    - name: Pull Docker image
      run: |
        docker pull pli11/gpgpusim:cuda_10_1
      shell: bash

    - name: Run Docker container
      run: |
        docker run -w /root -itd --name gpgpusim pli11/gpgpusim:cuda_10_1 /bin/bash
      shell: bash

    - name: Set up GPGPU-Sim
      run: |
        docker exec -i gpgpusim bash -c "
          cd /root/gpgpu-sim_distribution &&
          git checkout tags/v4.0.1 -b v401 &&
          make clean &&
          source setup_environment &&
          make -j"
      shell: bash

    - name: Clone and build vectorAdd
      run: |
        docker exec -i gpgpusim bash -c "
          source /root/gpgpu-sim_distribution/setup_environment &&
          cd /root &&
          git clone https://github.com/peiyi1/vectorAdd.git &&
          cd vectorAdd/ &&
          make -j"
      shell: bash

    - name: Run vectorAdd
      run: |
        docker exec -i gpgpusim bash -c "
          source /root/gpgpu-sim_distribution/setup_environment &&
          cd /root/vectorAdd/ &&
          cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* . &&
          ./vectorAdd > output.txt &&
          cat output.txt"
      shell: bash

    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: vectorAdd-output
        path: /root/vectorAdd/output.txt