name: proj1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Jimver/cuda-toolkit@v0.2.8
      id: cuda-toolkit
      with:
        cuda: '11.7.0'
    - name: Run tests
      run:
      echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
    - name: Run tests
      run:
      echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
