name: proj1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  steps:
  - uses: Jimver/cuda-toolkit@v0.2.8
    id: cuda-toolkit
    with:
      cuda: '11.7.0'
  - run: |
      echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
      echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
      nvcc -V

    runs-on: ubuntu-latest
    - uses: actions/checkout@v2
    - name: Build Project
      run: |
        cd proj/proj1/proj1a
        mkdir build
        cd build
        cmake ..
        make