name: Proj1B

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-and-run:
    runs-on: ubuntu-20.04
    container: 
      image: pli11/gpgpusim:cuda_10_1
      options: --user root
    env:
      CUDA_INSTALL_PATH: /usr/local/cuda-10.1
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set CUDA path globally
      run: |
        echo "CUDA_INSTALL_PATH=/usr/local/cuda-10.1" >> $GITHUB_ENV
        echo "CUDA_PATH=$CUDA_INSTALL_PATH" >> $GITHUB_ENV
        echo "PATH=$CUDA_INSTALL_PATH/bin:$PATH" >> $GITHUB_ENV
      shell: bash

    - name: Set up GPGPU-Sim
      run: |
        cd /root/gpgpu-sim_distribution
        git checkout tags/v4.0.1 -b v401
        make clean
        source setup_environment
        make -j
      shell: bash

    - name: Clone and build vectorAdd
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        cd /root
        git clone https://github.com/peiyi1/vectorAdd.git
        cd vectorAdd/
        make -j
      shell: bash
    - name: Run vectorAdd
      run: |
        source /root/gpgpu-sim_distribution/setup_environment
        cd /root/vectorAdd/
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* .
        ./vectorAdd > output.txt
        cat output.txt
      shell: bash

    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: vectorAdd-output
        path: /root/vectorAdd/output.txt