name: Proj1B

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Schedule to run at 00:00 UTC on the 1st of every month
    - cron: '0 0 1 * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    container: 
      image: pli11/gpgpusim:cuda_10_1

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GPGPU-Sim
      run: |
        cd /root/gpgpu-sim_distribution/
        git checkout tags/v4.0.1 -b v401
        make clean
        source setup_environment
        make

    - name: Clone and build vectorAdd
      run: |
        cd /root
        git clone https://github.com/peiyi1/vectorAdd.git
        cd vectorAdd/
        make clean
        make

    - name: Run vectorAdd
      run: |
        cd /root/vectorAdd/
        cp /root/gpgpu-sim_distribution/configs/tested-cfgs/SM7_QV100/* .
        ./vectorAdd > output.txt
        cat output.txt

    - name: Upload output
      uses: actions/upload-artifact@v2
      with:
        name: vectorAdd-output
        path: /root/vectorAdd/output.txt